# Generated by Django 5.1.4 on 2025-03-31 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('index_number', models.CharField(blank=True, max_length=20, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('student', 'Student'), ('absolwent', 'Absolwent'), ('prowadzacy', 'Prowadzący')], default='student', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('last_login_display', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('kolor', models.CharField(default='#3788d8', max_length=7)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
