# Generated by Django 5.1.4 on 2025-04-10 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotatkaKalendarzowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc_prywatna', models.TextField(blank=True, null=True)),
                ('tytul', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('kolor', models.CharField(default='#3788d8', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
